### ISSUE TITLE
MacOS imag-preview

### ISSUE THREAD

**Issue by Jac-Zac** [pystardust/ytfzf#44] opened 2021-02-27 21:35 UTC
Just to make you aware of this, preview of thumbnails doesn't work on macOS. The script download the images were it should, but it doesn't show them. It looks like the problem has to do with Überzug. I also tried to run fontpreview-ueberzug which won't work either. But I might also be wrong so if other people have mac they might be helpful. I also tried to used Überzug to preview images in ranger and It doesn't work. In ranger they use a preview for that works with iTerm terminal emulator. An example is imgcat

**Comment by westofer** [comment] 2021-02-28 04:36
can you post the output of `ueberzug version`?

mine is `18.1.9`

**Comment by Jac-Zac** [comment] 2021-02-28 09:04
> ueberzug version

Same... Does it work for you ?

**Comment by westofer** [comment] 2021-02-28 11:14
yes it works, are you using fish by any chance? becuase it doesn't work in fish for me

**Comment by Jac-Zac** [comment] 2021-02-28 15:18
> yes it works, are you using fish by any chance? becuase it doesn't work in fish for me
> 
> @Jac-Zac

I’m using zsh maybe we can have a discord server and talk there instead of just messaging ?

**Comment by westofer** [comment] 2021-02-28 15:24
sure @Jac-Zac

**Comment by Jac-Zac** [comment] 2021-02-28 15:47
https://discord.gg/FNym2zpK This is the discord server if we find helpful we might also expand it in the future and add it to README.md

**Comment by Z5483** [comment] 2021-03-03 14:01
Ueberzug relied on X11 so it wouldn't work in system that doesn't use X11

I know it's late but this might be helpful to some people who have this issue

**Comment by pystardust** [comment] 2021-03-03 16:01
Yes people on wayland are also having this issue. If anybody knows a terminal viewer that work on wayland + mac do let us know.

**Comment by cybarspace** [comment] 2021-03-03 18:47
> Yes people on wayland are also having this issue. If anybody knows a terminal viewer that work on wayland + mac do let us know.

Would w3m work?

**Comment by tinywrkb** [comment] 2021-03-03 19:45
@pystardust Ranger file manager has iTerm2 support for image previews, so maybe look at what it's doing. I don't have a Mac but it worked for me with Alacritty when pulling in [the graphics PR](https://github.com/alacritty/alacritty/pull/4763) that adds iTerm2 protocol & libsixel (though it looks like it won't be merged as it is).  
Ranger also has support for the image protocol of Kitty, and Kitty is also cross-platform.

**Comment by Z5483** [comment] 2021-03-04 02:52
I also like the way `neofetch` provides different image preview options for the user to choose from. I understand it would take a long time to implement, but it would be a neat and cool feature.

**Comment by dimitarvp** [comment] 2021-03-21 03:31
My `ueberzug` is also at `18.1.9` and I update `ytfzf` daily with a cron job. I am on the latest macOS (`11.2.3` as of today) and for me image previews don't work either. Tried inside iTerm2 and Alacritty, no dice in both.

I am not very keen on using a non-upstream version of Alacritty for now but might be willing to try pulling the above-mentioned graphics PR.

Is there anything us the macOS users can do to have the images previewed in our terminals?

**Comment by cybarspace** [comment] 2021-03-21 04:48
> Is there anything us the macOS users can do to have the images previewed in our terminals?

Try to change the code in ytfzf a bit to use iTerm2's own image renderer.

**Comment by Jac-Zac** [comment] 2021-03-21 09:56
I think we should do it like you said using iTerm's own image viewer like they have done [here](https://github.com/ranger/ranger/blob/a53f056cb2d9586ed97c7757a1e49d30d873c27d/ranger/ext/img_display.py). [This](https://iterm2.com/documentation-images.html) is the iTerm page. But you can't just use the imgcat script because fzf will just output the long string. If anybody has some ideas on what we can do I would be wiling to work together to try to solve it maybe on discord

**Comment by Z5483** [comment] 2021-03-22 15:17
I will try to implement different image viewers similar to `neofetch`, so user can choose whichever one they like. However, I think we should try to get `w3m` working as an alternative to `ueberzug`, since `w3m` should work on all system.

**Comment by pystardust** [comment] 2021-03-22 16:30
Yes I have tried w3mimg, it works well only with some terminals(urxvt)
Run this scirpt in a directory with images, do not give it any arguments.
You would need to give the path to your w3mimgdisplay binary that would be usually in `/usr/lib/w3m/` depending on your distro. I have copied mine to my `~/.bin/` here
```sh
#!/bin/sh

path_to_w3mimg=~/.bin/w3mimgdisplay

showimage () {
	printf '%b\n3;\n4\n' "0;1;20;20;$((FZF_PREVIEW_COLUMNS *55/10));$((FZF_PREVIEW_COLUMNS *55/10));;;;;$1"  | "$path_to_w3mimg" &>/dev/null 
}

if [ "$#" -eq 1 ]; then
	showimage "$1"
else
	fzf --preview "sh $0 {}" --preview-window "left"
fi

```

**Comment by pystardust** [comment] 2021-03-22 16:30
If this seems fine, then we could add this feature in ytfzf

**Comment by Z5483** [comment] 2021-03-26 13:05
Can someone with a mac to test this script?

**Comment by dimitarvp** [comment] 2021-03-26 13:12
@Z5483 Which script exactly? The one that uses `w3mimgdisplay`? I am not even sure how to install it on a Mac.

**Comment by Z5483** [comment] 2021-03-26 13:14
yes, the `w3mdisplay` script @pystardust posted few days ago.

``` cpp
​#!​/bin/sh​

path_to_w3mimg=​~​/.bin/w3mimgdisplay

​showimage​ () {
        ​printf​ ​'​%b\n3;\n4\n​'​ ​"​0;1;20;20;​$((​FZF_PREVIEW_COLUMNS ​*​55​/​10​))​;​$((​FZF_PREVIEW_COLUMNS ​*​55​/​10​))​;;;;;​$1​"​  ​|​ ​"​$path_to_w3mimg​"​ ​&​>​/dev/null 
}

​if​ [ ​"​$#​"​ ​-eq​ 1 ]​;​ ​then​
        showimage ​"​$1​"​
​else​
        fzf --preview ​"​sh ​$0​ {}​"​ --preview-window ​"​left​"​
​fi​
```

**Comment by dimitarvp** [comment] 2021-03-26 13:20
I can't run that script because I have no `~​/.bin/w3mimgdisplay` file. Doing `brew search w3mimgdisplay` didn't yield any results either. Any quick pointers how to install that binary? A quick search doesn't show it as a standalone package for Mac.

**Comment by westofer** [comment] 2021-03-26 13:20
install w3m

**Comment by dimitarvp** [comment] 2021-03-26 13:23
@westofer Installed it via `brew install w3m` but still no `w3mimgdisplay` binary in its directory tree -- or anywhere in $PATH. Only `w3m` and `w3mman`.

**Comment by westofer** [comment] 2021-03-26 13:26
`find / -name 'w3mimgdisplay`

mine was in `/usr/lib/w3m/w3mimgdisplay`

**Comment by dimitarvp** [comment] 2021-03-26 13:33
Already did that. It's nowhere to be found. I don't think the `homebrew` package includes it.

**Comment by Z5483** [comment] 2021-03-26 13:48
it might be related to this issue https://github.com/tats/w3m/issues/95

**Comment by dimitarvp** [comment] 2021-03-26 13:58
OK, cloned, compiled with the right options, changed the path in the above script, ran it in both iTerm2 and Alacritty (in a directory that has images in it) -- nothing appears on the left. Also waited for `fc-cache` to finish (it spiked for several seconds) just to make sure.

I am  seeing a blank black pane on the left. It has borders but no content.

I am new to w3m. Is there a way to test image showing in the terminal in isolation like with `imgcat`?

**Comment by dimitarvp** [comment] 2021-03-26 14:23
Another thing. Somewhere along the whole stuff an XQuartz installer popped up in the background which I didn't notice. I went through its installation and logged out and back in as the installer requested.

Results are the same. Maybe `w3m` has to be reconfigured and recompiled now that XQuartz is in place?

**Comment by Z5483** [comment] 2021-03-26 15:09
> Maybe w3m has to be reconfigured and recompiled now that XQuartz is in place?

This is outside of my knowledge since I'm not familiar with macOS. I think unlikely that you will have to recompile `w3m` since it does not depend neither XQuartz or Xlib.

> ran it in both iTerm2 and Alacritty (in a directory that has images in it), moved with the keyboard arrows until I got to an image in the file list -- nothing appears on the left

I will take at a look at the `w3mdisplay` script this weekend.

**Comment by Z5483** [comment] 2021-03-30 01:41
I can confirm that the w3mdisplay script results in the image flickers then disappears

**Comment by Jac-Zac** [comment] 2021-03-30 07:03
I think that is because w3m is not that great to display images in the first place

**Comment by pystardust** [comment] 2021-04-08 18:54
Could someone with a mac try using iTerms image viewer and make a script that would display an image given as input, with the give height and width at a given coordinate

**Comment by cheemeng** [comment] 2021-04-24 19:20
Instead of specifically relying on iTerm's imgcat (you can't even reposition the image, and there might be users of other terminals too such as Kitty or Wez's), perhaps you could take a look at [timg](https://github.com/hzeller/timg)?

It plays nicely with fzf too using the --preview parameter (might help you simplify maintenance of your menu system), heck you can even have timg output thumbnails into files instead of display, and simply cat the files out later.

**Comment by Euro20179** [comment] 2021-05-19 17:45
it is hard to implement image viewers that don't use ascii characters because of the way fzf's preview works, it basically only accepts ascii, the reason ueberzug works is because it's it's own window, w3m could possibly work, but whenever you try to use it the image is only on the screen for about .2 seconds.

viewers i tried that didn't work (all of which are proper image viewers)
1. kitty/icat
2. tycat
3. w3m
4. lsix/sixel

**Comment by jstkdng** [comment] 2023-05-02 23:03
Hey everyone, I have been developing this project, https://github.com/jstkdng/ueberzugpp, it is a drop in replacement for ueberzug but with aditional features such as sixel, kitty and iterm2 support. @Euro20179 has kindly added support for my project in ytfzf development branch and so far under linux all 4 outputs work (x11, kitty, sixel, iterm2).
U++ should also work in MacOS but I have not being able to test it since I don't own any apple devices. I'd be happy to help if someone is willing to test U++ in MacOS and finally close this issue.

**Comment by Jac-Zac** [comment] 2023-05-04 20:41
Trying to run the development branch to test it on mac gives me this error:

```bash
./ytfzf       
./ytfzf: line 3109: syntax error near unexpected token `;;'
./ytfzf: line 3109: `		youtube-dl) ${ytdl_path} -F "$1" ;;'```

**Comment by Jac-Zac** [comment] 2023-05-04 22:05
I get this: 
```
ls -l /usr/bin/sh 
lsd: /usr/bin/sh: No such file or directory (os error 2).```
In general though I use zsh:
```
echo $SHELL
/bin/zsh
```

Indeed by running:
```dash ytfzf``` it works

**Comment by Euro20179** [comment] 2023-05-04 22:08
Oh interesting, since /usr/bin/sh doesn't exist, it's probably running ytfzf with zsh which is unsupported.

I'll look into that later, for now run `dash ytfzf -t -T iterm2 search`, and see if the thumbnails work.

**Comment by Jac-Zac** [comment] 2023-05-04 22:24
Mmmm maybe it is just my problem and for some reason my sh is still liking to zsh and it should link to something like dash or bash. If I run it as you said it runs but the previewer doesn't work since it still try to run with zsh. If I change the shabang from sh to dash I get it to work though

**Comment by Euro20179** [comment] 2023-05-04 22:28
> Mmmm maybe it is just my problem and for some reason my sh is still liking to zsh

Nah, ls said that /usr/bin/sh doesn't exist in the first place, it's not linking to anything.

ytfzf uses `/usr/bin/env sh` as the shebang, try changing it to `/bin/env sh`, if that works I'll probably change the shebang to that.

**Comment by Jac-Zac** [comment] 2023-05-04 22:32
Oky but: `/usr/bin/env` does and when I run `/usr/bin/env sh` I'm quite sure I get a zsh shell so that is the problem. As I said using `/usr/bin/env dash` I get it to work on the other hand this path doesn't exist: `/bin/env`

**Comment by Jac-Zac** [comment] 2023-05-04 22:34
About the thumbnails not really and I'm not really sure what was the porblem since I get this:
<img width="1646" alt="image" src="https://user-images.githubusercontent.com/59306950/236343809-640a926d-0b2b-49ac-b229-07daa2f1a1ef.png">
and it seems to be stuck

**Comment by Jac-Zac** [comment] 2023-05-04 22:34
I have also tried with: `ueberzug` I do not get any error but I get the same behavior

**Comment by Euro20179** [comment] 2023-05-04 22:38
> Oky but: /usr/bin/env does and when I run /usr/bin/env sh I'm quite sure I get a zsh shell so that is the problem. As I said using /usr/bin/env dash I get it to work on the other hand this path doesn't exist: /bin/env

Oh, nvm then.

> I have also tried with: ueberzug I do not get any error but I get the same behavior

Ueberzug wont work, linux only,

apparently iterm2 is not in the newest version of ueberzugpp, so it needs to be compiled manually if your up for that, if you're not up for it, it's all good.

**Comment by Jac-Zac** [comment] 2023-05-04 22:40
Sorry I meant ueberzugcpp btw

**Comment by Jac-Zac** [comment] 2023-05-04 22:41
What exactly should I do ?  btw I meant that I have tried with ueberzugcpp not ueberzug

**Comment by Euro20179** [comment] 2023-05-04 22:47
> in my path with the name ueberzug

ytfzf checks specifically if you have `ueberzugpp` as a binary, so I would create a link called `ueberzugpp` to `ueberzug`, make sure you have `ueberzugpp` saved as `ueberzug` and `ueberzugpp`, as they're both used in ytfzf (I may change this later)

You could try the following:

ueberzugpp needs to be compiled manually (until iterm2 gets put into a release), as instructed on the [ueberzugpp readme](https://github.com/jstkdng/ueberzugpp), make sure to disable x11 support.

Put the binary somewhere in path

run `ytfzf -t -T iterm2 search` in the iterm2 terminal, theoretically images should show up

**Comment by jstkdng** [comment] 2023-05-04 23:27
X11 support should work in theory since MacOS has xquartz, the terminal also has to run through xquartz though. The same reason x11 works in wayland, only if the terminal is also running through xwayland.

**Comment by jstkdng** [comment] 2023-05-05 05:33
Managed to get a macos vm running and pushed a temporary fix for U++, turns out MacOS doesn't support procfs and uses different directories for pseudo-terminals, gonna have to work around that. It works at least.

![image](https://user-images.githubusercontent.com/52050345/236383577-b678f84b-344d-4de4-918c-95329d774362.png)

Sometimes this error appears though.

![image](https://user-images.githubusercontent.com/52050345/236383661-3d99e50b-565a-47bb-8d37-312d586b7e86.png)

**Comment by Euro20179** [comment] 2023-05-05 05:37
> It works at least.

Nice!

As for the error, it might've just failed to download the image.

**Comment by Jac-Zac** [comment] 2023-05-05 07:23
Ohhh sorry It works also for me but yesterday was very late and I made a symlink to `ueberzugcpp` instad of `ueberzugpp` my fault 🤦

**Comment by Euro20179** [comment] 2023-05-05 13:17
> I made a symlink to ueberzugcpp instad of ueberzugpp my fault

Lol, glad it works though!

**Comment by jstkdng** [comment] 2023-05-05 13:35
nice, I also fixed the proc issue. Now I think some more testing could be done by other users? I'll try to create a homebrew package.

**Comment by jstkdng** [comment] 2023-05-07 21:47
I have created a release with iterm2 and macos support. I've also created a homebrew script but it will take some time before it is included in homebrew-core.
I guess this could be closed unless there are other issues.

**Comment by Euro20179** [comment] 2023-05-07 23:18
> I guess this could be closed unless there are other issues.

Once I release 2.6.0 I will close this (assuming there are no other issues).

**Closed** 2023-05-12 14:34 UTC
Labels: thumbnails
