### ISSUE TITLE
UTF8

### ISSUE THREAD

**Issue by nereusx** [pystardust/ytfzf#69] opened 2021-03-03 21:47 UTC
![ytfzf-cols](https://user-images.githubusercontent.com/12963781/109876965-16c89d80-7c7b-11eb-8ae1-40c18da8a678.png)
I love it... but it needs utf8 support to adjust the columns

**Comment by westofer** [comment] 2021-03-04 02:50
please use mono-space fonts

**Comment by nereusx** [comment] 2021-03-04 04:13
It is monospace, actually bitmap font made by my hand.
The problem is the length of the strings. A utf8 string is using less space on display than strlen() returns. Every non 7bit ASCII character is encoded from 2 to 5 bytes.

**Comment by westofer** [comment] 2021-03-04 04:17
don't know much about fonts, but do you have a clue about fixing it?

also I find that the same amount of spaces `\s`  taking different amount of areas weird

![image](https://user-images.githubusercontent.com/50760091/109910620-983f2080-7cb9-11eb-8683-dfed5c776778.png)

**Comment by nereusx** [comment] 2021-03-04 05:52
I found the problem in the AWK's printf... actually has no parameter for the screen width.
This will help you:
```
#!/bin/sh
latin="Latin-text"
utf8s="Λάτιν-κειμ"

echo "Number of bytes"
echo $latin | wc -c
echo $utf8s | wc -c
echo "Number of utf8 characters"
echo $latin | wc -m
echo $utf8s | wc -m
```
btw, try `tput cols` it is better than `stty` :)

**Comment by pystardust** [comment] 2021-03-04 06:48
The parameter for the terminal width is determined by `stty` . Have you tried `tput cols`?
Let me know if the problem is fixed by replacing `stty size 2> /dev/null | cut -f2 -d' ' `  on line 127 with `tput cols`.

**Comment by nereusx** [comment] 2021-03-04 19:44
No, it wont fix it... I ll write you a printf for utf8 to solve this since I am much better in C. There is a more weird things when you have to deal with Chinese and Japanise, each character uses 2 columns. So, just wait me to write a u8printf utility...

**Comment by JojiiOfficial** [comment] 2021-03-04 20:03
So you want to make it depend on a non distributed c binary?

**Comment by nereusx** [comment] 2021-03-04 23:59
printf is standard unix command... see man 1 printf (the C function is man 3 printf). it has to work with %ls instead of %s, need a trick there too... you can fix this with the difference of (wc -c) - (wc -m)

**Comment by nereusx** [comment] 2021-03-05 00:25
Anyway, here it is to see/test/work how to work with this ... in C offcourse, https://github.com/nereusx/unix-utils/tree/master/u8printf

**Comment by pystardust** [comment] 2021-03-13 17:55
@nereusx 
Does using printf directly from coreutils rather than the awk's printf work? ( as you mention we could specify wide characters with `%ls`.  I don't quite understand what you mean by `wc -c` - `wc -m` this would give the number of wide characters, and then we try accounting for that?

**Comment by nereusx** [comment] 2021-03-14 11:15
In the printf("%nnns") - of [g]AWK - the nnn - the width - counts in bytes. you need the same but to count in wide characters. For details about the width in terminal, use `man 3 wcswidth`.

The difference of `wc -c` and `wc -m` is the actual width to pass to printf.

**Comment by woefe** [comment] 2021-04-13 19:58
I think the issue really are wide characters as @nereusx pointed out. I had a similar issue at https://github.com/woefe/ytcc/issues/62. You could pipe your tables through the `column` command, which takes care of wide characters. E.g. something like the following (which needs refinement, because I don't know how you handle the case when the separator is used in the title)

```patch
diff --git a/ytfzf b/ytfzf
index 87e1ce7..68a2e7b 100755
--- a/ytfzf
+++ b/ytfzf
@@ -343,7 +343,7 @@ format_menu () {
        if [ "$is_ext_menu" -eq 0 ]; then
                #dep_ck fzf here because it is only necessary to use here
                dep_ck "fzf"
-               menu_command='fzf -m --bind change:top --tabstop=1 --layout=reverse --delimiter="$tab_space" --nth=1,2 $FZF_DEFAULT_OPTS'
+               menu_command='column -t -s "$tab_space" -o "$tab_space" | fzf -m --bind change:top --tabstop=1 --layout=reverse --delimiter="$tab_space" --nth=1,2 $FZF_DEFAULT_OPTS'
                format_fzf
        else
                # Dmenu doesn't render tabs so removing it
```

You cannot solve the issue with `wc` because there are some characters that print as two characters wide. E.g. 😀 takes up the space of two characters on most terminals, but  `echo -n "😀" | wc -m` returns 1 and `echo -n "😀" | wc -c` returns 4

**Comment by pystardust** [comment] 2021-04-14 03:43
Interesting. The script initially used column. But due to portability issues (bsd and macos), it has been using printf with manual formatting. 
`column` in bsd does not support output field separator.

**Comment by pystardust** [comment] 2021-04-14 10:12
@woefe 
thanks , I have added column and it works great (currently in dev branch)

**Comment by pystardust** [comment] 2021-04-16 18:19
@nereusx 
I have implemented the column command, it seems to be formatting emojis very well. I suppose wide characters are taken care by column. Could you check if your font is being formatted properly.

**Comment by nereusx** [comment] 2021-04-17 15:02
It works perfectly :)

**Closed** 2021-04-21 18:49 UTC
Labels: bug
