### ISSUE TITLE
[BUG]: --channel-link option just echoes input URL

### ISSUE THREAD

**Issue by morganmay** [pystardust/ytfzf#600] opened 2022-11-04 19:31 UTC
### Describe the bug
When I try to use the `--channel-link="https://youtube.com/c/name"` option, it returns the same URL, rather than a URL in the form `https://youtube.com/channel/id`.

### To Reproduce
Entering
```
ytfzf --channel-link="https://www.youtube.com/c/SomeOrdinaryGamers"
```
results in the output:
```
https://www.youtube.com/c/SomeOrdinaryGamers
```

### Expected behavior
It isn't 100% clear from the documentation, but my understanding is that it should output a URL beginning with `https://youtube.com/channel/`.

### Information
 - OS: Arch Linux
 - Terminal: alacritty
 - Ytfzf version: git-1697.b71429e
- Output of `ls -l "$(which sh)"` (if you're using fish: `ls -l (which sh)`):
```
lrwxrwxrwx root root 4 B Sat Jan  8 10:31:11 2022 /usr/bin/sh ⇒ bash
```

**Comment by Euro20179** [comment] 2022-11-04 19:34
Your understanding of `--channel-link` is correct,

I can't reproduce this, i get the correct output

Try updating to the newest version of the development branch.

**Comment by morganmay** [comment] 2022-11-04 20:14
Ack, I forgot I had installed an AUR package. Didn't even need the dev version; current release works. Thanks!

**Comment by Euro20179** [comment] 2022-11-04 20:15
Ah cool, if it works on the current release, i'll close this.

**Closed by Euro20179** 2022-11-04 20:15 UTC
Labels: bug
