### ISSUE TITLE
Getting recommended videos from homepage of user and related videos.

### ISSUE THREAD

**Issue by ayan-iiitd** [pystardust/ytfzf#435] opened 2021-12-25 16:10 UTC
In YouTube API v3, one can get related videos of a video, and in v2 one could get the homepage recommendations as well, but Google stopped that in 2015.

Now I know this project discourages the use of the API (I think I read in one of the issues) and I totally respect that. And keeping that in mind I think I might have found a way to get these 2 things without the API, with some work from the users' side.

Reading through the script, I think in line 666(noice), I saw that curl is being used for fetching links from the main YouTube page. So this is the idea - 

- use a browser to login to your account
- copy the cookie that the browser saves in someplace easily accessible like in the same path as ytfzf's config file
- now since curl is being used, separate flags/parameters can be passed to ytfzf like -H, to make curl send the cookie through -c or -b to youtube.com to get videos from the homepage
- similarly, when a video is selected to be played, in the TUI it can show the scraped side panel of playing video, like the ones on the browser, with the user logged in.
- also, automated playlists of YouTube can be implemented by doing that in a loop.
- one potential problem is there might be a mismatch of the useragents, but that can be mitigated by either editing it or using a recommended browser, and also in this way copying the cookie will be standard across all users.

I would request the authors of this repo to look into this once.

**Comment by pystardust** [comment] 2021-12-25 16:19
Nice idea, i have tried and seen that its possible to scrape the side recommendations of a video with out api.
I didnt implement it due because it felt a lil too complex for a shell a script. Im thinking of implementing it fresh 
in python

**Comment by Euro20179** [comment] 2021-12-25 16:40
I have tried implementing this and its very inconsistent so i didnt go through with this.
Reimplementing this script in python might be a good idea but also calling something like fzf is annoying.

**Comment by pystardust** [comment] 2021-12-25 16:47
Yeah, like a new repo with a better name xd. We could use the default nurses in python rather than fzf

**Comment by Euro20179** [comment] 2021-12-25 17:40
> better name

ytfzfpy lol

> somethinf other than fzf

I think we should make it modular, so the default can be something else, but the usee could specify fzf if they wanted.

**Comment by ayan-iiitd** [comment] 2021-12-27 08:31
> Yeah, like a new repo with a better name xd. We could use the default nurses in python rather than fzf

If going for Python, then just make a GUI wrapper around it as well using pyqt or something, looking like youtube and just call it BetterTube. LOL!!!!

**Comment by Euro20179** [comment] 2021-12-27 14:12
> then just make a GUI wrapper around it as well using pyqt or something, 

this woukd peobably be a different peoject.
If you like web alternatives, look into invidious, if you want somethinf on the desktop look into freetube.

**Comment by Euro20179** [comment] 2022-01-15 23:48
@ayan-iiitd 

refer to [this](https://github.com/pystardust/ytfzf/issues/462#issuecomment-1013774146) comment

**Comment by slarrain** [comment] 2022-01-19 03:06
I can confirm that per [this](https://github.com/pystardust/ytfzf/issues/462#issuecomment-1013774146) comment it is working.

**Comment by Euro20179** [comment] 2022-01-28 20:32
Since I have added `recommended` as an add-on, I am doing to close this thread.

Instructions to get it
```sh
mkdir -p $HOME/.config/ytfzf/scrapers
curl 'https://raw.githubusercontent.com/pystardust/ytfzf/master/addons/scrapers/recommended' > $HOME/.config/ytfzf/scrapers/recommended
chmod +x $HOME/.config/ytfzf/scrapers/recommended
```

Copy the cookie header to $HOME/.config/ytfzf/recommended-cookie

If that cookie file does not exist, the scraper will give instructions on how to get it.

Feel free to reopen the thread if the scraper is broken (and you have properly copied the cookie header)

**Closed by Euro20179** 2022-01-28 20:32 UTC
