### ISSUE TITLE
[BUG]: On 2.5.5.rc-2 there are some jq errors when scraping subscriptions

### ISSUE THREAD

**Issue by kevenwyld** [pystardust/ytfzf#646] opened 2023-02-22 16:28 UTC
### Describe the bug

When running `ytfzf -f -c SI` with the following subscription file contents (simplified because it doesn't seem to make a difference) this error is reported:

```
Scraping subscriptions with instance: https://invidious.baczek.me
DL% UL%  Dled  Uled  Xfers  Live Total     Current  Left    Speed
--  --  58292     0     1     0  --:--:--  0:00:02 --:--:-- 26046
jq: error: syntax error, unexpected end (Unix shell quoting issues?) at <top-level>, line 1:
if (.videos|type) == "array" then .videos else if (.latestVideos|type) == "array" then .latestVideos end end
jq: error: Possibly unterminated 'if' statement at <top-level>, line 1:
if (.videos|type) == "array" then .videos else if (.latestVideos|type) == "array" then .latestVideos end end
jq: 2 compile errors
```

### To Reproduce

Using `2.5.5.rc-2`
1. Create subscription file using the --channel-link option on the videos URL.  Here is the contents of mine for reference though contents don't seem to make a difference:
```
https://www.youtube.com/channel/UC4PIO2pZaFKzI97uumFTNSg/videos
https://www.youtube.com/channel/UCeKpbMimEGgLM_0tnghfoVw/videos
https://www.youtube.com/channel/UC7pokUsRb6q2B0FOzSqQLlw/videos
https://www.youtube.com/channel/UCw3UZn1tcVe7pH3R6C3Gcng/videos
https://www.youtube.com/channel/UCCkSr3M8GXbS4txqPY7OMxQ/videos
https://www.youtube.com/channel/UC7Jf7t6BL4e74O53dL6arSw/videos
https://www.youtube.com/channel/UCY8gSLTqvs38bR9X061jFWw/videos
https://www.youtube.com/channel/UC-CubOaooNwC-3RBKUoAOQQ/videos
https://www.youtube.com/channel/UC7aAyIrjeH2RKciAXzdOaJA/videos
https://www.youtube.com/channel/UCKLIIdKEpjAnn8E76KP7sQg/videos
https://www.youtube.com/channel/UCyjwQ6oz4cqqtEcWGboSU3g/videos
https://www.youtube.com/channel/UChIs72whgZI9w6d6FhwGGHA/videos
https://www.youtube.com/channel/UCVI8Mfisni3GaobL1e2JOIQ/videos
https://www.youtube.com/channel/UC2wdo5vU7bPBNzyC2nnwmNQ/videos
```
2. Run `ytfzf -f -c SI`

### Expected behavior

an fzf list of videos matching the subscription query

### Screenshots

From above:

```
Scraping subscriptions with instance: https://invidious.baczek.me
DL% UL%  Dled  Uled  Xfers  Live Total     Current  Left    Speed
--  --  58292     0     1     0  --:--:--  0:00:02 --:--:-- 26046
jq: error: syntax error, unexpected end (Unix shell quoting issues?) at <top-level>, line 1:
if (.videos|type) == "array" then .videos else if (.latestVideos|type) == "array" then .latestVideos end end
jq: error: Possibly unterminated 'if' statement at <top-level>, line 1:
if (.videos|type) == "array" then .videos else if (.latestVideos|type) == "array" then .latestVideos end end
jq: 2 compile errors
```

### Information
 - OS: archlinux
 - Terminal: Alacritty
 - Ytfzf version: 2.5.5.rc-2
- Output of `ls -l "$(which sh)"` (if you're using fish: `ls -l (which sh)`):
```
] > ls -l (which sh)
lrwxrwxrwx 1 root root 4 Feb  1 23:38 /usr/sbin/sh -> bash*
```
 - (if is a thumbnail issue) run `ytfzf --thumbnail-log=log.txt` and post the file: not a thumbnail issue

### Additional information

The behavior at first was reporting errors from curl (didn't save the output so I can't post it unfortunately).  After updating today to `curl 7.88.1-2` from `7.88.1-1` those curl errors are gone, so it seems there was a problem with the arch curl package for a brief period.  If trying to reproduce on archlinux make sure the system is completely up to date.

This just started happening yesterday.  Curl did go through 2 updates in the last 2 days but downgrading to `7.88.0-4` makes no difference so I think that's just coincidence.

Thanks!

**Comment by Euro20179** [comment] 2023-02-22 16:38
It seems that the problem is that `jq-git` (from the aur) works perfectly fine, but `jq` from the main repo does not.

Newer versions of jq may have some syntax that the old versions dont.

**Comment by kevenwyld** [comment] 2023-02-22 16:41
@Euro20179 I think it might be the other way around.  jq-git hasn't been updated since 2018 and depends on python2.  Unless I'm looking at the wrong package.

**Comment by Euro20179** [comment] 2023-02-22 16:48
ok this should be fixed

**Comment by kevenwyld** [comment] 2023-02-22 16:51
Yep, working great now.  Thanks!

**Closed** 2023-03-06 16:22 UTC
Labels: bug
