### ISSUE TITLE
[BUG]: Ueberzug thumbnails don't show on initial search

### ISSUE THREAD

**Issue by mozirilla213** [pystardust/ytfzf#644] opened 2023-02-17 23:15 UTC
### Describe the bug
On an initial search, ueberzug thumbnails are not shown and instead an error message like `/usr/bin/ytfzf: 2410: cannot create : Directory nonexistent` is shown (for the ueberzug switch on the `preview_no_img ()` function) and when scrolling videos: `/usr/bin/ytfzf: 2530: cannot create : Directory nonexistent` (for the ueberzug switch on the `preview_display_image ()` function)

However when you make the next search (having run `ytfzf -s -t`) with the same search term, the thumbnails are shown correctly

This happens because the `$UEBERZUG_FIFO` variable is not set correctly (it's empty) because it is not save to `"$session_cache_dir/environment"` on the initial search

### To Reproduce
`ytfzf -s -t`, search, `<Esc>`, search with same search term, `<Esc>`, search with other search term

### Workaround
If you put the line `echo "UEBERZUG_FIFO='$UEBERZUG_FIFO'" >> "$session_cache_dir/environment"` in the `preview_start ()` function right after `UEBERZUG_FIFO="$session_temp_dir/ytfzf-ueberzug-fifo"`,  at least the the first search shows thumbnails correctly, but on the next first search with other search term the problem persists.

### Additional context
I think this wasn't happening in a ytfzf version from late last year

### Information
 - OS: Arch Linux
 - Terminal: Alacritty
 - Ytfzf version: 2.5.4
- /usr/bin/sh ⇒ dash
- I tried running `ytfzf --thumbnail-log=log.txt` and `ytfzf -t --thumbnail-log=log.txt`, but the file was empty even after searching and quiting

**Comment by Euro20179** [comment] 2023-02-18 00:18
I Believe this is a duplicate of #632

**Comment by mozirilla213** [comment] 2023-02-18 21:05
Yeah I think so, but I just tried with bash with the same issue.

Also I tried development branch from `edfaf31` to `73cb529` and what happens is the first thumbnail after search (so the `preview_no_img ()` function) looks like it wants to load and show the image (a black flash of an image appears) but it doesn't; whereas the other thumbnails when scrolling (so the `preview_display_image ()` function) apparently never finish loading (fzf shows a loading icon); both with dash and bash.

But on same branch, the commit from that day `1f8849c` up to `eaea5fe` work fine, so it's commit `34e6114` by removing  file descriptor 3 for ueberzug where the issue reappeared and that re-regression hasn't been fixed

So should I reopen 632?

**Comment by Euro20179** [comment] 2023-02-18 22:15
oh damn i thought fd 3 was unused i can just add it back

**Comment by KAN7A** [comment] 2023-02-20 14:23
I have a similar issue, no version would display thumbnails, the arch community build displayed the exact same error as #632 ,on the AUR version there was a loading indicator in the corner that never finishes, same with installing fron source i am pretty sure, on version 2.5.3 thumbnails are shown but overlap with the upload date, 2.5.2 is the latest working version for me. Thumbnail log was empty on all versions.

**Comment by kevenwyld** [comment] 2023-02-23 06:16
I'm also having this issue (no thumbnails at all).  I reconstructed some of the fd 3 bits from above locally and it does resolve it for me.  Specifically I restored [this line](https://github.com/pystardust/ytfzf/commit/34e6114f7342d0ecbf676bb5f00ac3a6f5199abd#diff-a2ab70d1ccc85ac09c9540a95a34bb5fbe9a25b67ab7a2cc98ba5329b4391396L2488) and [this case](https://github.com/pystardust/ytfzf/commit/34e6114f7342d0ecbf676bb5f00ac3a6f5199abd#diff-a2ab70d1ccc85ac09c9540a95a34bb5fbe9a25b67ab7a2cc98ba5329b4391396L2515).

I'm still missing some stuff since subscriptions don't have thumbnails, but at least it confirms that it was needed.

**Comment by Euro20179** [comment] 2023-02-23 13:25
```diff
diff --git a/ytfzf b/ytfzf
index 181627e..12a2a03 100755
--- a/ytfzf
+++ b/ytfzf
@@ -2531,6 +2531,7 @@ preview_start () {
 			rm -f "$UEBERZUG_FIFO"
 			mkfifo "$UEBERZUG_FIFO"
 			ueberzug layer --parser json < "$UEBERZUG_FIFO"  > "$thumbnail_debug_log" 2>&1 &
+            exec 3>"$UEBERZUG_FIFO"
 			;;
 		chafa|chafa-16|chafa-tty|catimg|catimg-256|swayimg|swayimg-hyprland) : ;;
 		imv)
@@ -2556,7 +2557,8 @@ preview_start () {
 preview_stop () {
 	thumbnail_viewer=$1
 	case $thumbnail_viewer in
-	    chafa|chafa-16|chafa-tty|catimg|catimg-256|ueberzug) : ;;
+        ueberzug) exec 3>&- ;;
+	    chafa|chafa-16|chafa-tty|catimg|catimg-256) : ;;
 	    mpv)
 		kill "$mpv_pid"
 		rm "$MPV_SOCKET" > /dev/null 2>&1
@@ -3141,6 +3143,7 @@ internal_action_preview_img () {
     read -r thumbnail_viewer < "$var_fifo"
     printf "%s" ytfzf_video_json_file > "$var_fifo"
     read -r ytfzf_video_json_file < "$var_fifo"
+
     video_json_file="$ytfzf_video_json_file"
 
     line_file="$*"
```

Here's the patch, if anyone wants to try it feel free, I'll try it later.

**Closed** 2023-03-06 16:22 UTC
Labels: bug

**Comment by mozirilla213** [comment] 2023-03-07 10:32
Thanks for the fix!
